# Generated by Django 4.2.21 on 2025-05-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarduser',
            name='total_trials',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboarduser',
            name='trials_inprogress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboarduser',
            name='trials_missingcontact',
            field=models.IntegerField(default=0),
        ),
    ]
